import React, { useState } from "react";
import { Policy, AgencyProfile, formatSumAssuredDisplay } from "../types";
import { ArrowLeft, Download } from "lucide-react";
import jsPDF from "jspdf";

interface PolicyDetailsViewProps {
  policy: Policy;
  onBack: () => void;
  agencyProfile?: AgencyProfile | null;
}

export default function PolicyDetailsView({ policy, onBack, agencyProfile }: PolicyDetailsViewProps) {
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  // ── Helpers ─────────────────────────────────────────────────
  const fmtCurrency = (val?: number) => (val || 0).toLocaleString("en-IN");
  const formatDate = (dateStr?: string) => {
    if (!dateStr) return "—";
    try {
      const parts = dateStr.split("-");
      if (parts.length === 3) {
        const year = parts[0];
        const monthIdx = parseInt(parts[1], 10) - 1;
        const day = parseInt(parts[2], 10);
        const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
        if (monthIdx >= 0 && monthIdx < 12) return `${day < 10 ? "0" + day : day} ${months[monthIdx]} ${year}`;
      }
      return dateStr;
    } catch { return dateStr; }
  };

  const getDocDownloadUrl = (doc: any) => {
    const filename = doc.storedName || (doc.path ? doc.path.split("/").pop() : "");
    if (filename) return `/api/policies/download/${encodeURIComponent(filename)}?originalName=${encodeURIComponent(doc.originalName || filename)}`;
    return doc.path || "#";
  };

  // ── Pure jsPDF A4 PDF ────────────────────────────────────────
  const handleDownloadPdf = () => {
    if (isGeneratingPdf) return;
    setIsGeneratingPdf(true);
    try {
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const W = 210, H = 297, mL = 14, mR = 14, cW = W - mL - mR;
      let y = 0, page = 1;
      const ts = new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

      const hasCompanyProfile = !!(agencyProfile?.companyName || agencyProfile?.agencyName);
      const companyName = hasCompanyProfile
        ? (agencyProfile?.companyName || agencyProfile?.agencyName || "").toUpperCase()
        : "Company Profile Not Configured";

      const mobileStr = agencyProfile?.mobileNumber || agencyProfile?.mobile || "";
      const emailStr = agencyProfile?.email || "";
      const gstStr = agencyProfile?.gstNumber ? `GSTIN: ${agencyProfile.gstNumber}` : "";

      const footer = () => {
        pdf.setFontSize(7.5); pdf.setTextColor(120, 120, 130);
        pdf.text(
          `Generated by ${companyName}`,
          W / 2, H - 10, { align: "center" }
        );
        if (hasCompanyProfile) {
          const contactLine = [mobileStr ? `Ph: ${mobileStr}` : "", emailStr, gstStr].filter(Boolean).join("  ·  ");
          if (contactLine) {
            pdf.setFontSize(6.5); pdf.setTextColor(140, 140, 150);
            pdf.text(contactLine, W / 2, H - 6.5, { align: "center", maxWidth: cW });
          }
        }
        pdf.setFontSize(6.5); pdf.setTextColor(150, 150, 160);
        pdf.text("This is a computer generated document.", W / 2, H - 3, { align: "center" });
      };
      const space = (n: number) => { if (y + n > H - 18) { footer(); pdf.addPage(); page++; y = 18; } };
      const secHdr = (n: string, t: string) => {
        space(12);
        pdf.setFillColor(245, 245, 247); pdf.roundedRect(mL, y, cW, 8, 1, 1, "F");
        pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(30, 30, 40);
        pdf.text(`${n}  ${t.toUpperCase()}`, mL + 3, y + 5.5); y += 11;
      };
      const field = (lbl: string, val: string, x: number, w: number) => {
        pdf.setFontSize(7); pdf.setFont("helvetica", "bold"); pdf.setTextColor(130, 130, 140);
        pdf.text(lbl.toUpperCase(), x, y);
        pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(20, 20, 30);
        const lines = pdf.splitTextToSize(val || "—", w - 2);
        pdf.text(lines, x, y + 4.5);
        return 4.5 + lines.length * 4;
      };
      const twoCol = (l1: string, v1: string, l2: string, v2: string) => {
        space(14);
        const h1 = field(l1, v1, mL, cW / 2);
        const h2 = field(l2, v2, mL + cW / 2, cW / 2);
        y += Math.max(h1, h2) + 5;
      };
      const fourCol = (cols: [string, string][]) => {
        space(14); const w = cW / 4; let max = 0;
        cols.forEach(([l, v], i) => { const h = field(l, v, mL + i * w, w); if (h > max) max = h; });
        y += max + 5;
      };

      // ── Simplified Company Profile Branding Header ──────────────
      pdf.setFillColor(25, 25, 35);
      pdf.rect(0, 0, W, 30, "F");

      // Company name (left)
      pdf.setFontSize(13); pdf.setFont("helvetica", "bold"); pdf.setTextColor(255, 255, 255);
      pdf.text(companyName, mL, 12, { maxWidth: cW * 0.65 });

      if (hasCompanyProfile) {
        // Contact & GST Line
        const cParts = [];
        if (mobileStr) cParts.push(`Ph: ${mobileStr}`);
        if (emailStr) cParts.push(emailStr);
        if (gstStr) cParts.push(gstStr);

        if (cParts.length) {
          pdf.setFontSize(7); pdf.setFont("helvetica", "normal"); pdf.setTextColor(180, 180, 200);
          pdf.text(cParts.join("  ·  "), mL, 19, { maxWidth: cW * 0.65 });
        }
      } else {
        pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(240, 160, 160);
        pdf.text("Please configure Company Profile in Gateway Settings", mL, 19);
      }

      // Policy Number & Date (top right)
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(255, 255, 255);
      pdf.text(`Policy No: ${policy.policyNumber || "—"}`, W - mR, 12, { align: "right" });
      pdf.setFontSize(7); pdf.setFont("helvetica", "normal"); pdf.setTextColor(180, 180, 200);
      pdf.text(`Generated: ${new Date().toLocaleDateString("en-IN")}`, W - mR, 18, { align: "right" });
      y = 36;

      secHdr("01", "Policy Overview");
      fourCol([
        ["Login Date", formatDate((policy as any).businessLoginDate || policy.startDate)],
        ["Business Type", (policy as any).businessSubtype || "FRESH"],
        ["Policy Tenure", policy.policyTenure ? `${policy.policyTenure} Yr` : "1 Yr"],
        ["Policy Status", (policy as any).policyStatus || "Not Set"],
      ]);

      secHdr("02", "Customer Information");
      twoCol("Customer Name", policy.customerName, "Customer Type", (policy as any).customerType || "Individual");
      twoCol("Date of Birth", formatDate(policy.customerBirthday), "Gender", (policy as any).gender || "—");
      twoCol("Marital Status", (policy as any).maritalStatus || "—", "Occupation", policy.occupation || "—");
      twoCol("Annual Income", policy.annualIncome ? `Rs. ${policy.annualIncome}` : "—", "Phone", policy.customerPhone || "—");
      twoCol("WhatsApp", (policy as any).whatsappNumber || "—", "Email", policy.customerEmail || "—");
      twoCol("Height", policy.height || (policy as any).healthDetails?.height || "—", "Weight", policy.weight || (policy as any).healthDetails?.weight || "—");

      secHdr("03", "Address Details");
      twoCol("House / Flat", policy.houseFlat || "—", "Street / Area", policy.streetArea || "—");
      twoCol("Landmark", policy.landmark || "—", "City", policy.city || "—");
      twoCol("District", policy.district || "—", "State", policy.state || "—");
      twoCol("Pincode", policy.pincode || "—", "Full Address", policy.address || "—");

      secHdr("04", "Family Members");
      if (!policy.familyMembersList?.length) {
        space(8); pdf.setFontSize(8); pdf.setFont("helvetica", "italic"); pdf.setTextColor(140, 140, 150);
        pdf.text("No family members covered under this policy.", mL, y); y += 8;
      } else {
        policy.familyMembersList.forEach((m: any) => {
          space(11); pdf.setFontSize(8); pdf.setFont("helvetica", "bold"); pdf.setTextColor(20, 20, 30);
          pdf.text(`${m.name || "—"}  (${m.relationship || "—"})`, mL, y);
          pdf.setFont("helvetica", "normal"); pdf.setTextColor(100, 100, 110);
          const hw = [m.height ? `Height: ${m.height}` : "", m.weight ? `Weight: ${m.weight}` : ""].filter(Boolean).join("   ");
          const hwStr = hw ? `   ${hw}` : "";
          pdf.text(`DOB: ${formatDate(m.dob)}   Gender: ${m.gender || "—"}${hwStr}   Pre-existing: ${m.hasPreExistingCondition || "No"}`, mL + 3, y + 4.5);
          y += 11;
        });
      }

      secHdr("05", "Policy Information");
      twoCol("Insurance Company", policy.companyName, "Policy Category", policy.policyType);
      twoCol("Product Name", policy.productName || "—", "Policy Number", policy.policyNumber || "—");
      twoCol("Sum Assured", formatSumAssuredDisplay(policy.sumAssured, policy.sumAssuredType), "Premium Amount", `Rs. ${fmtCurrency(policy.premiumAmount)}`);
      twoCol("Payment Frequency", policy.premiumFrequency, "Cashback", policy.cashbackEnabled ? `Yes (Rs. ${fmtCurrency(policy.cashbackAmount || 0)})` : "No");
      twoCol("Payment Mode", (policy as any).paymentMode || "Direct", "Finance Vendor", (policy as any).paymentMode === "Finance/EMI" ? ((policy as any).financeVendor || "—") : "—");
      twoCol("Start Date", formatDate(policy.startDate), "Next Due Date", formatDate(policy.nextDueDate));
      twoCol("Expiry Date", formatDate(policy.expiryDate), "Premium Status", policy.premiumStatus || "—");

      secHdr("06", "Commission Details");
      twoCol("Applied Payout %", `${(policy as any).appliedPayoutPercentage || 0}%`, "Expected Commission", `Rs. ${fmtCurrency((policy as any).expectedCommission)}`);
      if (policy.businessType === "RENEWAL") {
        if ((policy as any).renewalManagerName || (policy as any).renewalExecutiveName) {
          twoCol("Renewal Manager", (policy as any).renewalManagerName || "—", "Renewal Executive", (policy as any).renewalExecutiveName || "—");
        }
      } else {
        if ((policy as any).bmName) twoCol("Branch Manager", (policy as any).bmName, "Team Manager", (policy as any).teamManagerName || "—");
        if ((policy as any).teamLeaderName || (policy as any).callerName) twoCol("Team Leader", (policy as any).teamLeaderName || "—", "Sales Executive", (policy as any).callerName || (policy as any).tseName || "—");
      }

      secHdr("07", "Documents");
      if (!policy.documents?.length) {
        space(8); pdf.setFontSize(8); pdf.setFont("helvetica", "italic"); pdf.setTextColor(140, 140, 150);
        pdf.text("No documents attached.", mL, y); y += 8;
      } else {
        policy.documents.forEach((doc: any, idx: number) => {
          space(10); pdf.setFontSize(8); pdf.setFont("helvetica", "bold"); pdf.setTextColor(20, 20, 30);
          pdf.text(`${idx + 1}. ${doc.originalName || doc.storedName || `Document ${idx + 1}`}`, mL + 2, y);
          pdf.setFont("helvetica", "normal"); pdf.setTextColor(100, 100, 110);
          pdf.text(`Uploaded: ${doc.uploadedAt ? doc.uploadedAt.split("T")[0] : "—"}`, mL + 2, y + 4.5);
          y += 11;
        });
      }

      if (policy.notes) {
        secHdr("08", "Notes & Remarks");
        space(10); pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(40, 40, 50);
        const nl = pdf.splitTextToSize(policy.notes, cW);
        pdf.text(nl, mL, y); y += nl.length * 4.5 + 6;
      }

      footer();
      pdf.save(`Policy_${(policy.policyNumber || "POLICY").replace(/[^a-zA-Z0-9_-]/g, "_")}_Details.pdf`);
    } catch (err: any) {
      console.error("PDF error:", err);
      alert("PDF generation failed. Please try again.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  // ── Derived values ───────────────────────────────────────────
  const bType = policy.businessType === "RENEWAL"
    ? "Renewal"
    : ((policy.businessSubtype || "").toUpperCase() === "PORT" || policy.businessType === "PORT" || Boolean(policy.portabilityDetails?.previousInsuranceCompany))
      ? "Portability (Port)"
      : "Fresh";

  const premiumBadge = policy.premiumStatus === "Paid"
    ? "bg-emerald-50 text-emerald-700 border-emerald-300"
    : policy.premiumStatus === "Overdue"
      ? "bg-rose-50 text-rose-700 border-rose-300"
      : "bg-amber-50 text-amber-700 border-amber-300";

  const policyBadge = (policy as any).policyStatus === "Issued"
    ? "bg-emerald-50 text-emerald-700 border-emerald-300"
    : (policy as any).policyStatus === "Cancelled"
      ? "bg-rose-50 text-rose-700 border-rose-300"
      : "bg-amber-50 text-amber-700 border-amber-300";

  // ── Sub-components ───────────────────────────────────────────
  const Field = ({ label, value, mono = false }: { label: string; value?: string | null; mono?: boolean }) => (
    <div className="py-3 border-b border-slate-100 last:border-0">
      <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">{label}</dt>
      <dd className={`text-[13px] font-bold text-slate-900 leading-snug break-words ${mono ? "font-mono" : ""}`}>
        {value || <span className="text-slate-400 font-normal">—</span>}
      </dd>
    </div>
  );

  const SecTitle = ({ num, label }: { num: string; label: string }) => (
    <div className="flex items-center gap-3 mb-5 mt-1">
      <span className="w-6 h-6 rounded-full bg-slate-900 text-white text-[11px] font-black flex items-center justify-center shrink-0 leading-none">
        {num}
      </span>
      <h2 className="text-[12px] font-extrabold text-slate-900 uppercase tracking-widest">{label}</h2>
    </div>
  );

  const Rule = () => <hr className="border-t border-slate-200 my-8" />;

  // ── Render ───────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-slate-100 py-6 px-4 sm:px-6 lg:px-8">

      {/* ─── HEADER BAR ─────────────────────────────────────── */}
      <div className="max-w-5xl mx-auto mb-5">
        <div className="bg-white border border-slate-200 rounded-xl px-5 py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-sm">
          <div>
            <button
              type="button"
              onClick={onBack}
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-slate-800 transition cursor-pointer mb-3"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Back to Policy Ledger
            </button>
            <h1 className="text-[17px] font-extrabold text-slate-900 tracking-tight">Policy Details</h1>
            <div className="flex flex-wrap items-center gap-2 mt-2">
              <span className="text-xs text-slate-500">Business Type: <strong className="text-slate-800">{bType}</strong></span>
              <span className="text-slate-300 text-xs">·</span>
              <span className="text-xs text-slate-500">Policy No: <strong className="font-mono text-slate-800">{policy.policyNumber || "—"}</strong></span>
              <span className="text-slate-300 text-xs">·</span>
              <span className={`px-2 py-0.5 rounded border text-[11px] font-bold ${premiumBadge}`}>{policy.premiumStatus || "Pending"}</span>
              <span className={`px-2 py-0.5 rounded border text-[11px] font-bold ${policyBadge}`}>{(policy as any).policyStatus || "Not Set"}</span>
            </div>
          </div>
          <div className="shrink-0">
            <button
              type="button"
              onClick={handleDownloadPdf}
              disabled={isGeneratingPdf}
              className="flex items-center gap-2 px-4 py-2.5 bg-slate-900 hover:bg-slate-700 text-white text-xs font-bold rounded-lg transition cursor-pointer disabled:opacity-50 shadow-sm"
            >
              <Download className={`w-3.5 h-3.5 ${isGeneratingPdf ? "animate-bounce" : ""}`} />
              {isGeneratingPdf ? "Generating..." : "Download PDF"}
            </button>
          </div>
        </div>
      </div>

      {/* ─── FORM BODY ──────────────────────────────────────── */}
      <div className="max-w-5xl mx-auto bg-white border border-slate-200 rounded-xl shadow-sm px-8 pt-8 pb-10">

        {/* SECTION 1 ── Policy Overview */}
        <SecTitle num="1" label="Policy Overview" />
        <dl className="grid grid-cols-2 sm:grid-cols-4 gap-x-8">
          <Field label="Business Login Date" value={formatDate((policy as any).businessLoginDate || policy.startDate)} mono />
          <Field label="Business Type" value={bType} />
          <Field label="Business Subtype" value={(policy as any).businessSubtype || "FRESH"} />
          <Field label="Policy Tenure" value={policy.policyTenure ? `${policy.policyTenure} ${policy.policyTenure === 1 ? "Year" : "Years"}` : "1 Year"} />
          <Field label="Policy Status" value={(policy as any).policyStatus || "Not Set"} />
        </dl>

        <Rule />

        {/* SECTION 2 ── Customer Information */}
        <SecTitle num="2" label="Customer Information" />
        <dl className="grid grid-cols-2 sm:grid-cols-4 gap-x-8">
          <div className="col-span-2 py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Customer Name</dt>
            <dd className="text-[15px] font-extrabold text-slate-900">{policy.customerName}</dd>
          </div>
          <Field label="Customer Type" value={(policy as any).customerType || "Individual"} />
          <Field label="Date of Birth" value={formatDate(policy.customerBirthday)} mono />
          <Field label="Gender" value={(policy as any).gender || "—"} />
          <Field label="Marital Status" value={(policy as any).maritalStatus || "—"} />
          <Field label="Occupation" value={policy.occupation || "—"} />
          <Field label="Annual Income" value={policy.annualIncome ? `₹${policy.annualIncome}` : "—"} mono />
          <Field label="Height" value={policy.height || (policy as any).healthDetails?.height || "—"} mono />
          <Field label="Weight" value={policy.weight || (policy as any).healthDetails?.weight || "—"} mono />
          <Field label="Phone" value={policy.customerPhone} mono />
          <Field label="WhatsApp Number" value={(policy as any).whatsappNumber || "—"} mono />
          <div className="col-span-2 py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Email</dt>
            <dd className="text-[13px] font-bold text-slate-900">{policy.customerEmail || "—"}</dd>
          </div>
        </dl>

        <Rule />

        {/* SECTION 3 ── Address Details */}
        <SecTitle num="3" label="Address Details" />
        <dl className="grid grid-cols-2 sm:grid-cols-4 gap-x-8">
          <Field label="House / Flat No." value={policy.houseFlat || "—"} />
          <Field label="Street / Area" value={policy.streetArea || "—"} />
          <Field label="Landmark" value={policy.landmark || "—"} />
          <Field label="City" value={policy.city || "—"} />
          <Field label="District" value={policy.district || "—"} />
          <Field label="State" value={policy.state || "—"} />
          <Field label="Pincode" value={policy.pincode || "—"} mono />
          <div className="col-span-2 sm:col-span-4 py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Complete Address</dt>
            <dd className="text-[13px] font-bold text-slate-900 leading-relaxed">
              {policy.address ||
                [policy.houseFlat, policy.streetArea, policy.landmark, policy.city, policy.district, policy.state, policy.pincode]
                  .filter(Boolean).join(", ") || "—"}
            </dd>
          </div>
        </dl>

        <Rule />

        {/* SECTION 4 ── Family Members */}
        <SecTitle num="4" label="Family Members" />
        {(!policy.familyMembersList || policy.familyMembersList.length === 0) ? (
          <p className="text-sm text-slate-400 italic">No family members covered under this policy.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border border-slate-200 rounded-lg overflow-hidden">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  {["Member Name", "Relationship", "Date of Birth", "Gender", "Height", "Weight", "Health Status", "Pre-existing Disease"].map(h => (
                    <th key={h} className="px-4 py-2.5 text-[11px] font-semibold text-slate-500 uppercase tracking-wider">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {policy.familyMembersList.map((fam: any, idx: number) => (
                  <tr key={idx}>
                    <td className="px-4 py-2.5 font-bold text-slate-900">{fam.name || "—"}</td>
                    <td className="px-4 py-2.5 text-slate-600">{fam.relationship || "—"}</td>
                    <td className="px-4 py-2.5 font-mono text-slate-600">{formatDate(fam.dob)}</td>
                    <td className="px-4 py-2.5 text-slate-600">{fam.gender || "—"}</td>
                    <td className="px-4 py-2.5 font-mono text-slate-600">{fam.height || "—"}</td>
                    <td className="px-4 py-2.5 font-mono text-slate-600">{fam.weight || "—"}</td>
                    <td className="px-4 py-2.5 text-slate-600">{fam.medicalDetails || fam.healthStatus || "Healthy"}</td>
                    <td className="px-4 py-2.5">
                      <span className={`px-2 py-0.5 rounded border text-[11px] font-bold ${fam.hasPreExistingCondition === "Yes" ? "bg-rose-50 text-rose-700 border-rose-200" : "text-slate-400 border-slate-200"}`}>
                        {fam.hasPreExistingCondition || "No"}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <Rule />

        {/* SECTION 5 ── Policy Information */}
        <SecTitle num="5" label="Policy Information" />
        <dl className="grid grid-cols-2 sm:grid-cols-4 gap-x-8">
          <div className="col-span-2 py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Insurance Company</dt>
            <dd className="text-[13px] font-bold text-slate-900">{policy.companyName}</dd>
          </div>
          <Field label="Policy Category" value={policy.policyType} />
          <Field label="Product Name" value={policy.productName || "—"} />
          <Field label="Policy Number" value={policy.policyNumber} mono />
          <div className="py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Sum Assured</dt>
            <dd className="text-[16px] font-extrabold text-teal-700 font-mono">{formatSumAssuredDisplay(policy.sumAssured, policy.sumAssuredType)}</dd>
          </div>
          <div className="py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Premium Amount</dt>
            <dd className="text-[16px] font-extrabold text-slate-900 font-mono">₹{fmtCurrency(policy.premiumAmount)}</dd>
          </div>
          <Field label="Payment Frequency" value={policy.premiumFrequency} />
          <Field label="Cashback" value={policy.cashbackEnabled ? `Yes (₹${fmtCurrency(policy.cashbackAmount || 0)})` : "No"} mono={Boolean(policy.cashbackEnabled)} />
          <Field label="Payment Mode" value={(policy as any).paymentMode || "Direct"} />
          {(policy as any).paymentMode === "Finance/EMI" && (
            <Field label="Finance Vendor" value={(policy as any).financeVendor || "—"} />
          )}
          <Field label="Start Date" value={formatDate(policy.startDate)} mono />
          <Field label="Next Premium Due Date" value={formatDate(policy.nextDueDate)} mono />
          <Field label="Policy Expiry Date" value={formatDate(policy.expiryDate)} mono />
          <div className="py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Premium Status</dt>
            <dd>
              <span className={`inline-block px-2.5 py-0.5 rounded border text-[11px] font-bold ${premiumBadge}`}>
                {policy.premiumStatus}
              </span>
            </dd>
          </div>
        </dl>

        <Rule />

        {/* SECTION 6 ── Commission Details */}
        <SecTitle num="6" label="Commission Details" />
        <dl className="grid grid-cols-2 sm:grid-cols-4 gap-x-8">
          <Field label="Applied Payout %" value={`${(policy as any).appliedPayoutPercentage || 0}%`} mono />
          <div className="py-3 border-b border-slate-100">
            <dt className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Expected Commission</dt>
            <dd className="text-[15px] font-extrabold text-slate-900 font-mono">₹{fmtCurrency((policy as any).expectedCommission)}</dd>
          </div>
          <Field label="Commission Status" value={(policy as any).commissionStatus || "Unpaid"} />
          <Field label="Source Type" value={(policy as any).sourceType || "Sales Team"} />
          {policy.advisorName && (
            <Field label="Partner Advisor" value={`${policy.advisorName} ${policy.advisorCode ? `(${policy.advisorCode})` : ""}`} />
          )}
          {policy.businessType !== "RENEWAL" && (policy as any).bmName && <Field label="Branch Manager" value={(policy as any).bmName} />}
          {policy.businessType !== "RENEWAL" && (policy as any).teamManagerName && <Field label="Team Manager" value={(policy as any).teamManagerName} />}
          {policy.businessType !== "RENEWAL" && (policy as any).teamLeaderName && <Field label="Team Leader" value={(policy as any).teamLeaderName} />}
          {policy.businessType !== "RENEWAL" && ((policy as any).callerName || (policy as any).tseName) && (
            <Field label="Sales Executive / TSE" value={(policy as any).callerName || (policy as any).tseName} />
          )}
          {policy.businessType === "RENEWAL" && (policy as any).renewalManagerName && <Field label="Renewal Manager" value={(policy as any).renewalManagerName} />}
          {policy.businessType === "RENEWAL" && (policy as any).renewalExecutiveName && <Field label="Renewal Executive" value={(policy as any).renewalExecutiveName} />}
        </dl>

        <Rule />

        {/* SECTION 7 ── Documents */}
        <SecTitle num="7" label="Documents" />
        {(!policy.documents || policy.documents.length === 0) ? (
          <p className="text-sm text-slate-400 italic">No documents attached to this policy.</p>
        ) : (
          <ul>
            {policy.documents.map((doc: any, idx: number) => (
              <li key={idx} className="flex items-center justify-between py-3 border-b border-slate-100 last:border-0">
                <div className="min-w-0 mr-4">
                  <p className="text-sm font-bold text-slate-900 truncate">{doc.originalName || doc.storedName || `Document ${idx + 1}`}</p>
                  <p className="text-[11px] text-slate-400 font-mono mt-0.5">
                    Uploaded: {doc.uploadedAt ? formatDate(doc.uploadedAt.split("T")[0]) : "—"}
                  </p>
                </div>
                <a
                  href={getDocDownloadUrl(doc)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900 border border-slate-200 hover:border-slate-400 px-3 py-1.5 rounded-lg transition shrink-0"
                >
                  <Download className="w-3.5 h-3.5" /> Download
                </a>
              </li>
            ))}
          </ul>
        )}

        {/* SECTION 8 ── Notes (conditional) */}
        {policy.notes && (
          <>
            <Rule />
            <SecTitle num="8" label="Notes & Remarks" />
            <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{policy.notes}</p>
          </>
        )}

        {/* ── Footer ─────────────────────────────────────────── */}
        <div className="mt-10 pt-5 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-400">
          <span>Policy Master CRM — Official Policy Record</span>
          <span className="font-mono">{new Date().toLocaleDateString("en-IN")}</span>
        </div>

      </div>
    </div>
  );
}
